# Python-Numpy
本笔记基本架构出自[Python深度学习：NumPy数组库](https://www.bilibili.com/video/BV1H84y1g7RE/?p=3)。
## 数组基础
导入Numpy时，通常会给其一个别名“np”，即import numpy as np。
### 数据类型
#### 整数型数组与浮点型数组
为了克服列表的缺点，一个numpy数组只容纳一种数据类型，以节约内存。为方便起见，可将numpy数组简单分为整数型数组与浮点型数组。

In [1]:
import numpy as np
# 创建整数型数组
arr1 = np.array([1, 2, 3])
print(arr1)

# 创建浮点型数组
arr2 = np.array([1.0, 2, 3])
print(arr2)

[1 2 3]
[1. 2. 3.]


注意，我们使用print输出numpy数组后，元素之间没有逗号，这有两个好处：
- 可以与python的列表区分开
- 避免逗号与小数点之间的混淆

#### 同化定理
在实际操作中要注意：
- 往整数型数组里插入浮点数，该浮点数会自动被截断为整数
- 往浮点型数组里插入整数，该整数会被自动升级为浮点数

In [2]:
arr1[0] = 100.9
print(arr1)

arr2[1] = 10
print(arr2)

[100   2   3]
[ 1. 10.  3.]


#### 共同改变定理
一个人不能改变集体，但只要全体共同改变，就可以成功。

要实现整数型数组和浮点型数组之间的转化，规范的方法是使用astype()方法。

In [4]:
# 整数型数组
arr1 = np.array([1, 2, 3])
print(arr1)

# 整数型 -> 浮点型
arr2 = arr1.astype(float)
print(arr2)

# 浮点型 -> 整数型
arr3 = arr2.astype(int)
print(arr3)

[1 2 3]
[1. 2. 3.]
[1 2 3]


除了上述方法，只要满足共同改变定理，整数型数组和浮点型数组仍然可以互相转换。最常见的就是整数型数组在运算过程中升级为浮点型数组，示例如下。

In [7]:
# 整数型数组
arr = np.array([1, 2, 3])
print(arr)

# 整数型数组与浮点数做运算
print(arr + 1.0)

# 整数型数组遇到除法（即便结果还是整数）
print(arr / 1)

# 整数型数组与浮点型数组做运算
print(arr + np.array([1.0, 2.0, 3.0]))

[1 2 3]
[2. 3. 4.]
[1. 2. 3.]
[2. 4. 6.]


整数型数组很好升级，但浮点型数组运算过程中一般不会降级。

### 数组维度
#### 一维数组与二维数组

In [12]:
# 一维数组
arr1 = np.ones(3)
print(arr1, arr1.shape)

# 二维数组
arr2 = np.ones((1, 3))
print(arr2, arr2.shape)

# 三维数组
arr3 = np.ones((1, 1, 3))
print(arr3, arr3.shape)

[1. 1. 1.] (3,)
[[1. 1. 1.]] (1, 3)
[[[1. 1. 1.]]] (1, 1, 3)


#### 不同维度数组之间的转换
不同维度数组之间的转换需要用到数组的重塑方法reshape()，该方法需要传入重塑后的形状。该方法神奇的地方在于，给定了其他维度的数值，剩下一个维度可以填-1，让它自己去计算。

In [16]:
# 创建一维数组
arr1 = np.arange(10)
print(arr1)

# 升级为二维数组
arr2 = arr1.reshape(1, -1)
print(arr2)

# 维度重塑
arr2 = arr2.reshape(2, 5)
print(arr2)

# 降级为一维数组
arr1 = arr2.reshape(-1)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


## 数组的创建
数组的创建主要有四种方法：
- 创建指定数组
- 创建递增数组
- 创建同值数组
- 创建随机数组
### 创建指定数组
当明确数组每一个元素的具体数值时，可以使用np.array()函数，将python列表转化为numpy数组。

In [18]:
# 创建一维数组——向量
arr1 = np.array([1, 2, 3])
print(arr1, arr1.shape)

# 创建二维数组——行矩阵
arr2 = np.array([[1, 2, 3]])
print(arr2, arr2.shape)

# 创建二维数组——列矩阵（比行矩阵更消耗内存）
arr3 = np.array([[1], [2], [3]])
print(arr3, arr3.shape)

# 创建二维数组——矩阵
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr4, arr4.shape)

[1 2 3] (3,)
[[1 2 3]] (1, 3)
[[1]
 [2]
 [3]] (3, 1)
[[1 2 3]
 [4 5 6]] (2, 3)


### 创建递增数组
递增数组使用np.arange()函数进行创建（array_range）。

In [20]:
arr1 = np.arange(10) # 从0开始，到10之前结束
arr2 = np.arange(10, 20) # 从10开始，到20之前结束
arr3 = np.arange(1, 21, 2) # 从1开始，到21之前结束，步长为2
arr1, arr2, arr3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]))

### 创建同值数组
通常使用np.zeros()和np.ones()函数。

In [21]:
arr1 = np.zeros((1, 3))
arr2 = np.ones((1, 3))
arr3 = 3.14 * np.ones((2, 3))
arr1, arr2, arr3

(array([[0., 0., 0.]]),
 array([[1., 1., 1.]]),
 array([[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]]))

可以发现，上面创建的全0和全1数组都是浮点型数组，考虑是周到的。

### 创建随机数组
主要使用np.random()系列函数，见下面的例子。

In [27]:
# 0-1均匀分布的浮点型随机数组
arr1 = np.random.random(5)
arr2 = 40 * np.random.random(5) + 60 # 60-100均匀分布

# 整数型随机数组
arr3 = np.random.randint(10, 100, (1, 15)) # 范围是10-99的整数，形状为(1,15)

# 服从正态分布的随机数组
arr4 = np.random.normal(0, 1, (2, 3))
arr5 = np.random.randn(2, 3) # 0-1标准正态分布的简写

arr1, arr2, arr3, arr4, arr5

(array([0.29117915, 0.66859123, 0.8948586 , 0.65823544, 0.59687329]),
 array([87.43029301, 75.31346101, 86.58644735, 75.40227379, 92.02031509]),
 array([[40, 24, 33, 80, 30, 89, 54, 13, 16, 93, 28, 17, 52, 16, 87]]),
 array([[-0.27096695, -0.63908846, -0.18533542],
        [-2.29437879, -0.71562511, -0.59187023]]),
 array([[-0.57585843, -1.66008542,  0.47614616],
        [ 0.42465438,  1.12066817, -1.34409039]]))

## 数组的索引
### 访问数组元素
与python列表一致，访问numpy数组元素时使用中括号，索引由0开始。

In [28]:
# 创建向量
arr1 = np.arange(1, 10)

# 访问元素
print(arr1[3]) # 正着访问
print(arr1[-1]) # 倒着访问

# 修改数组元素
arr1[3] = 100
arr1

4
9


array([  1,   2,   3, 100,   5,   6,   7,   8,   9])

### 花式索引
用逗号可以实现同时访问数组或矩阵的多个元素，具体见下面的例子。

In [32]:
arr1 = np.arange(0, 90, 10)
arr2 = np.arange(1, 17).reshape(4, 4)

# 向量的花式索引
print(arr1[[0, 2]]) # 索引为0和2
# 矩阵的花式索引
print(arr2[[0, 1], [0, 1]]) # 0行0列和1行1列
# 修改数组元素
arr2[[0, 1, 2, 3], [3, 2, 1, 0]] = 100
arr2

[ 0 20]
[1 6]


array([[  1,   2,   3, 100],
       [  5,   6, 100,   8],
       [  9, 100,  11,  12],
       [100,  14,  15,  16]])

### 访问数组切片
向量切片与列表切片的操作完全一致。

In [34]:
# 向量切片
arr1 = np.arange(10)
arr1, arr1[1:4], arr1[1:], arr1[:4], arr1[2:-2], arr1[1:-1:2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 2, 3]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3]),
 array([2, 3, 4, 5, 6, 7]),
 array([1, 3, 5, 7]))

In [42]:
# 矩阵切片（类似）
arr2 = np.arange(1, 21).reshape(4, 5)
print(arr2)
print(arr2[1:3, 1:-1])
print(arr2[::3, ::2]) # 跳跃采样

# 提取矩阵的行
print(arr2[2, :])
print(arr2[1:3, :])
print(arr2[2]) # 提取行的简写（但提取列不可简写）

# 提取矩阵的列
print(arr2[:, 2])
print(arr2[:, 1:3])
print(arr2[:, 2].reshape((-1, 1)), arr2[:, 2].reshape((-1, 1)).shape) # 向量升级为矩阵

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]]
[[ 1  3  5]
 [16 18 20]]
[11 12 13 14 15]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[ 3  8 13 18]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
[[ 3]
 [ 8]
 [13]
 [18]] (4, 1)


### 数组切片仅是视图
numpy数组的切片仅是原数组的一个视图，并不会创建新的变量。

In [43]:
arr = np.arange(10)
cut = arr[:3]
print(cut)
cut[0] = 100
print(cut)

[0 1 2]
[100   1   2]


我们发现，修改数组的切片后，原数组也被修改，这样的设计十分节省内存。在深度学习中，将多次使用arr[:]=<表达式>代替arr=<表达式>。

如果确实需要创建新变量（这种情况很少），可以使用copy()函数。

In [46]:
arr = np.arange(10)
copy = arr[:3].copy()
copy[0] = 100
print(copy)
print(arr)

[100   1   2]
[0 1 2 3 4 5 6 7 8 9]


### 数组赋值仅是绑定
与numpy数组的切片一样，numpy数组完整地赋值给另外一个数组，也只是绑定。换言之，numpy数组之间的赋值并不会创建新的变量。此特性仍然是为了节约空间，破局的方法仍然是使用copy()函数。

In [47]:
arr1 = np.arange(10)
arr2 = arr1
arr2[0] = 100
arr1, arr2 # 原数组也被修改

(array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9]),
 array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9]))

## 数组的变形
### 数组的转置
数组的转置方法T只对矩阵（包括行矩阵和列矩阵）有效，因此需要先把数组转化为矩阵。

In [49]:
arr1 = np.arange(1, 4)
arr2 = arr1.reshape((1, -1))
arr3 = arr2.T
arr4 = arr1.reshape((-1, 1)) #一步到位变成列矩阵
arr1, arr2, arr3, arr4

(array([1, 2, 3]),
 array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]),
 array([[1],
        [2],
        [3]]))

In [50]:
# 矩阵的转置
arr1 = np.arange(4).reshape(2, 2)
arr2 = arr1.T
arr1, arr2

(array([[0, 1],
        [2, 3]]),
 array([[0, 2],
        [1, 3]]))

### 数组的翻转
数组的翻转方法有两个，一个是上下翻转的np.flipud()，表示up-down；一个是左右翻转的np.fliplr()，表示left-right。其中向量只能使用上下翻转。

In [52]:
# 向量的翻转
arr = np.arange(10)
print(arr)
print(np.flipud(arr))

# 矩阵的翻转
arr = np.arange(20).reshape(4, 5)
print(arr)
print(np.flipud(arr))
print(np.fliplr(arr))

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


### 数组的重塑
数组的重塑主要使用reshape()方法，这里不再赘述。
### 数组的拼接
主要使用concatenate()方法，矩阵拼接要设定在哪个维度进行拼接。

In [61]:
# 向量的拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate([arr1, arr2])
print(arr1, arr2, arr3)

# 矩阵的拼接（需要注意维度）
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
# 按第一个维度（行）进行拼接
arr3 = np.concatenate([arr1, arr2], axis=0)
# 按第二个维度（列）进行拼接
arr4 = np.concatenate([arr1, arr2], axis=1)
print(arr1, arr1.shape)
print(arr2, arr2.shape)
print(arr3, arr3.shape)
print(arr4, arr4.shape)

[1 2 3] [4 5 6] [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]] (2, 3)
[[ 7  8  9]
 [10 11 12]] (2, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] (2, 6)


注意，向量和矩阵不能进行拼接，必须先把向量升级成行矩阵。
### 数组的分裂

In [62]:
# 向量的分裂
arr = np.arange(10, 100, 10)
print(arr)
arr1, arr2, arr3 = np.split(arr, [2, 8])
arr1, arr2, arr3

[10 20 30 40 50 60 70 80 90]


(array([10, 20]), array([30, 40, 50, 60, 70, 80]), array([90]))

np.split()函数中，给出的第二个参数[2, 8]表示在索引[2]和索引[8]的位置截断。

In [66]:
# 矩阵的分裂
arr = np.arange(1, 9).reshape(2, 4)
print(arr)
# 按第一个维度（行）分裂
arr1, arr2 = np.split(arr, [1], axis=0)
print(arr1)
print(arr2)
# 按第二个维度（列）分裂
arr1, arr2, arr3 = np.split(arr, [1, 3], axis=1)
print(arr1)
print(arr2)
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]
[[5 6 7 8]]
[[1]
 [5]]
[[2 3]
 [6 7]]
[[4]
 [8]]


## 数组的运算
### 数组与系数之间的运算

In [68]:
arr = np.arange(1, 9).reshape(2, 4)
print(arr)
print(arr + 10)
print(arr / 10)
print(arr ** 2)
print(arr // 6)

[[1 2 3 4]
 [5 6 7 8]]
[[11 12 13 14]
 [15 16 17 18]]
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[0 0 0 0]
 [0 1 1 1]]


### 数组与数组之间的运算
同维度数组间的运算即对应元素之间的运算，这里仅以矩阵为例，向量之间的操作与之相同。

In [69]:
arr1 = np.arange(-1, -9, -1).reshape(2, 4)
arr2 = -arr1
print(arr1, arr2)
print(arr1 + arr2)
print(arr1 * arr2)  

[[-1 -2 -3 -4]
 [-5 -6 -7 -8]] [[1 2 3 4]
 [5 6 7 8]]
[[0 0 0 0]
 [0 0 0 0]]
[[ -1  -4  -9 -16]
 [-25 -36 -49 -64]]


### 广播机制
不同形状的数组之间的运算有以下规则：
- 如果是向量与矩阵之间做运算，向量自动升级为行矩阵；
- 如果某矩阵是行矩阵或列矩阵，则其被广播，以适配另一个矩阵的形状。

#### 向量被广播（比较常见的情况）
当一个形状为(x, y)的矩阵与一个向量做运算时，要求该向量的形状必须为y（或者x，对应升级为列矩阵），运算时向量会自动升级成形状为(1, y)的行矩阵，该形状为(1, y)的行矩阵再自动被广播为形状为(x, y)的矩阵，这样就能与另一个矩阵的形状适配了。

In [113]:
arr1 = np.array([-100, 0, 100])
arr2 = np.random.random((10, 3)) # 创建服从0-1均匀分布的10*3矩阵
print(arr1 * arr2)

[[0.28934033 0.39443914 0.75955818]
 [0.98580754 0.31519313 0.79829376]
 [0.66906777 0.46124244 0.76423519]
 [0.589682   0.14880533 0.77335451]
 [0.40297189 0.53650821 0.3420899 ]
 [0.58420765 0.43756407 0.07747611]
 [0.53865425 0.00600806 0.21616473]
 [0.30535625 0.53297371 0.33621359]
 [0.49116148 0.81256314 0.88110561]
 [0.53746223 0.93730133 0.30421803]]
[[-28.93403289   0.          75.95581794]
 [-98.58075428   0.          79.8293762 ]
 [-66.9067768    0.          76.42351926]
 [-58.96819986   0.          77.33545101]
 [-40.29718909   0.          34.2089902 ]
 [-58.42076537   0.           7.74761085]
 [-53.86542524   0.          21.6164734 ]
 [-30.53562457   0.          33.62135908]
 [-49.11614842   0.          88.11056088]
 [-53.74622302   0.          30.42180334]]


#### 列矩阵被广播
当一个形状为(x, y)的矩阵与一个列矩阵做运算时，要求该列矩阵的形状必须为(x, 1)，该形状为(x, 1)的列矩阵再自动被广播为形状为(x, y)的矩阵，这样就能与另一个矩阵的形状适配了。

In [73]:
arr1 = np.arange(3).reshape(3, 1)
arr2 = np.ones((3, 5))
print(arr1 * arr2)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]]


#### 行矩阵和列矩阵同时被广播
当一个形状为(1, y)的行矩阵和一个形状为(x, 1)的列矩阵做运算时，这俩矩阵都会被自动广播为形状为(x, y)的矩阵，这样就互相适配了。

In [75]:
arr1 = np.arange(3)
arr2 = np.arange(3).reshape(3, 1)
print(arr1 * arr2)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


## 数组的函数
### 矩阵乘积
- 前面出现的乘法都是“逐元素相乘”，这里介绍线性代数中的矩阵乘法，使用np.dot()函数即可。
- 当矩阵乘积中混有向量时，根据需求，其可充当行矩阵，也可充当列矩阵，但混有向量时输出结果必为向量。

In [78]:
# 向量与向量的乘积
arr1 = np.arange(5)
arr2 = np.arange(5)
print(np.dot(arr1, arr2))

# 向量与矩阵的乘积
arr1 = np.arange(5)
arr2 = np.arange(15).reshape(5, 3)
print(np.dot(arr1, arr2))

# 矩阵与矩阵的乘积
arr1 = np.arange(10).reshape(5, 2)
arr2 = np.arange(16).reshape(2, 8)
print(np.dot(arr1, arr2))

30
[ 90 100 110]
[[  8   9  10  11  12  13  14  15]
 [ 24  29  34  39  44  49  54  59]
 [ 40  49  58  67  76  85  94 103]
 [ 56  69  82  95 108 121 134 147]
 [ 72  89 106 123 140 157 174 191]]


### 数学函数
最重要、常见的几个数学函数：
- 绝对值函数abs()

- 三角函数sin()等

- 指数函数exp()

- 对数函数log()（需要不同底数用换底公式解决）

### 聚合函数（参数可选维度）
- 最大值函数max()和最小值函数min()

- 累加函数sum()和累乘函数prod()

- 均值函数mean()和标准差函数std()

考虑到大型数组难免有缺失值，以上聚合函数遇到缺失值时会报错，因此出现了聚合函数的安全版本，即计算时忽略缺失值，如nansum()等。

## 布尔型数组
### 创建布尔型数组

In [82]:
# 数组与数字作比较
arr = np.arange(1, 7).reshape(2, 3)
print(arr)
print(arr >= 4)

# 数组与同维数组作比较
arr1 = np.arange(1, 6)
arr2 = np.flipud(arr1)
print(arr1)
print(arr2)
print(arr1 > arr2)

# 同时比较多个条件（与（&），或（|），非（~））
arr = np.arange(1, 10)
print(arr)
print((arr < 4) | (arr > 6))

[[1 2 3]
 [4 5 6]]
[[False False False]
 [ True  True  True]]
[1 2 3 4 5]
[5 4 3 2 1]
[False False False  True  True]
[1 2 3 4 5 6 7 8 9]
[ True  True  True False False False  True  True  True]


### 布尔型数组中True的数量
有三个关于True数量的有用函数，分别是np.sum(), np.any(), np.all()。
- np.sum()函数可以统计布尔型数组里True的个数

In [86]:
# 创建一个包含10000个数的正态分布数组
arr = np.random.randn(10000)
# 统计该分布中绝对值小于1的元素个数
num = np.sum(np.abs(arr) < 1)
print(num) # 理论值在6827左右

6794


- np.any()函数：只要布尔型数组里含有一个或以上的True，就返回True。

In [87]:
# 判断两个数组是否有共同元素
arr1 = np.arange(1, 10)
arr2 = np.flipud(arr1)
print(np.any(arr1 == arr2))

True


- np.all()函数：当布尔型数组里全是True时，才返回True。

In [94]:
# 模拟英语六级的成绩，创建100000个样本
arr = np.random.normal(500, 70, 100000)
# 判断是否所有考生的分数都高于250分
print(np.all(arr > 250))

False


从结果来看，尽管3 $\sigma$ 准则告诉我们有99.87%的考生成绩高于500-3*70=290分，但仍然有最终成绩低于250分的裸考者。

### 布尔型数组作为掩码
若一个普通数组和一个布尔型数组的维度相同，可以将布尔型数组作为普通数组的掩码，这样可以对普通数组中的元素作筛选。

In [97]:
# 示例1：数组与数字作比较
arr = np.arange(1, 13).reshape(3, 4)
print(arr > 4)
# 筛选出arr > 4的元素
print(arr[arr > 4])

# 示例2：同维数组筛选
arr1 = np.arange(1, 10)
arr2 = np.flipud(arr1)
print(arr1 > arr2)
print(arr1[arr1 > arr2])
print(arr2[arr1 > arr2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]
[False False False False False  True  True  True  True]
[6 7 8 9]
[4 3 2 1]


### 满足条件的元素所在位置
假设一个很长的数组，我想知道满足某个条件的元素们所在的索引位置，此时使用np.where()函数。

In [111]:
arr = np.random.normal(500, 70, 1000)
print(np.where(arr > 650)) # 结果是一个元组，包含索引数组和数据类型
print(np.where(arr == np.max(arr)))

(array([  3,   5, 134, 197, 220, 256, 293, 405, 533, 537, 546, 575, 703,
       731, 743, 838, 916, 919, 951], dtype=int64),)
(array([405], dtype=int64),)


## 从数组到张量
### 数组与张量
PyTorch作为当前首屈一指的深度学习库，其将Numpy的语法尽数吸收，作为自己处理数组的基本语法，且运算速度从使用CPU的数组进步到使用GPU的张量。

Numpy和PyTorch的语法几乎一致，具体表现为：
- np对应torch；

- 数组array对应张量tensor；

- Numpy的n为数组对应PyTorch的n阶张量。

数组与张量之间可以互相转换：
- 数组转张量：ts = torch.tensor(arr)；

- 张量转数组：arr = np.array(ts)。

### 语法不同点
PyTorch只是少量修改了Numpy的部分函数，具体可以查阅[Python深度学习：NumPy数组库](https://www.bilibili.com/video/BV1H84y1g7RE/?p=3)。
这里展示几个重要的函数变化：
|函数类型|NumPy|PyTorch|用法区别|
|:---:|:---:|:---:|:---:|
|数组拼接|np.concatenate()|torch.cat()|无|
|矩阵乘积|np.dot()|torch.matmul()|无|
|矩阵乘积|np.dot(v, v)|torch.dot()|无|
|矩阵乘积|np.dot(m, v)|torch.mv()|无|
|矩阵乘积|np.dot(m, m)|torch.mm()|无|